title: Projet

tabs:
  #-----------------------------------------------------------------------------
  content:
    label: Description
    icon: text
    columns:
      #-------------------------------------------------------------------------
      - width: 1/4
        sections:
          files: sections/files
          vimeos: sections/vimeos
      #-------------------------------------------------------------------------
      - width: 1/2
        sections:
          content:
            type: fields
            fields:
              autoid: fields/autoid
              cdate: fields/cdate
              categories: fields/categories
              yearbegin:
                label: Année de début
                type: number
                icon: calendar
                required: true
                translate: false
                width: 1/2
              yearend:
                label: Année de fin
                help: (optionnel)
                type: number
                icon: calendar
                translate: false
                width: 1/2
              metas: fields/metas
              text:
                extends: fields/markdown
                label: Description
              aside:
                extends: fields/markdown
                label: Informations complémentaires
      #-------------------------------------------------------------------------
      - width: 1/4
        sections:
          info:
            type: info
            headline: ''
            text: >
              Page créée le <b>{{ page.cdate.toDate('d/m/Y') }}</b><br>
              Dernière modification le <b>{{ page.modified('d/m/Y') }}</b> à <b>{{ page.modified('H:i') }}</b><br>
          notes: sections/notes
  #-----------------------------------------------------------------------------
  tab_cover:
    label: Médias
    icon: image
    columns:
      #-------------------------------------------------------------------------
      - width: 1/4
        sections:
          files: sections/files
          vimeos: sections/vimeos
      #-------------------------------------------------------------------------
      - width: 3/4
        fields:
          cover_raw:
            label: Couverture
            type: select
            options: query
            query: page.allowed_cover
            translate: false
            required: true
            width: 2/3

          color:
            label: Couleur
            type: color
            placeholder: '000000'
            editableAlpha: false
            translate: false
            required: true
            width: 1/3
            default: '#FFFFFF'

          gallery: fields/gallery
  #-----------------------------------------------------------------------------
  tab_related:
    label: Projets connexes
    icon: page
    fields:
      related:
        label: Projets connexes
        type: pages
        max: 2
        size: large
        translate: false
        layout: cards
        help: |
          <b>Attention</b> : seuls les projets publiés peuvent être sélectionnés.
        empty: Aucun projet en page d'accueil
        query: site.find("projects").children.listed
        image:
          query: page.panelPreviewCover
          back: black
  #-----------------------------------------------------------------------------
  tab_files:
    label: Fichiers
    icon: file-image
    sections:
      files_all:
        extends: sections/files
        layout: cards
        size: tiny
        limit: 10000

      vimeos_all:
        extends: sections/vimeos
        layout: cards
        size: tiny
        limit: 10000
