title: Projet
num: '{{ page.modified }}'

tabs:

  content:
    label: Description
    icon: text
    columns:
      - width: 1/3
        sections:
          info:
            type: info
            headline: ''
            text: >
              Page créée le <b>{{ page.cdate.toDate('d/m/Y') }}</b><br>
              Dernière modification le <b>{{ page.modified('d/m/Y') }}</b> à <b>{{ page.modified('H:i') }}</b><br>
          files: sections/files
          vimeos: sections/vimeos

      - width: 2/3
        sections:
          content:
            type: fields
            fields:
              autoid: fields/autoid
              cdate: fields/cdate
              categories: fields/categories
              yearbegin:
                label: Année de début
                type: number
                icon: calendar
                required: true
                translate: false
                width: 1/2
              yearend:
                label: Année de fin
                help: (optionnel)
                type: number
                icon: calendar
                translate: false
                width: 1/2
              metas: fields/metas
              text:
                extends: fields/markdown
                label: Description
              aside:
                extends: fields/markdown
                label: Informations complémentaires

  tab_cover:
    label: Médias
    icon: image
    columns:
      - width: 1/3
        sections:
          info:
            type: info
            headline: ''
            text: >
              Page créée le <b>{{ page.cdate.toDate('d/m/Y') }}</b><br>
              Dernière modification le <b>{{ page.modified('d/m/Y') }}</b> à <b>{{ page.modified('H:i') }}</b><br>
          files: sections/files
          vimeos: sections/vimeos

      - width: 2/3
        fields:
          cover_raw:
            label: Couverture
            type: select
            options: query
            query: page.medias
            translate: false
            required: true
            width: 2/3

          color:
            label: Couleur
            type: text
            placeholder: '000000'
            before: '#'
            maxlength: 6
            minlength: 6
            translate: false
            required: true
            width: 1/3
            default: '000000'
            help: "TODO: color picker"

          gallery: fields/gallery

  tab_related:
    label: Projets connexes
    icon: page
    fields:
      related:
        label: Projets connexes
        type: pages
        max: 2
        size: large
        translate: false
        layout: cards
        help: |
          <b>Attention</b> : seuls les projets publiés peuvent être sélectionnés.
        empty: Aucun projet en page d'accueil
        query: site.find("projects").children.listed
        image:
          query: page.panelPreviewCover
          back: black
