title: Project
icon: picture-o
pages: false
files:
  fields:
    _file: _file

fields:
  pf: _previewfiles

  tab1:
    label: Général
    type: tabs

  title: _title

  yearBegin:
    type: number
    label: Année du projet
    default: 2018
    icon: calendar-o
    required: true
    translate: false
    width: 1/2

  yearEnd:
    type: number
    label: Année de fin projet (optionnel)
    icon: calendar-o
    placeholder: ''
    translate: false
    width: 1/2

  categories: _categories

  tab2:
    label: Couverture
    type: tabs

  cover_help:
    type: info
    text: >
      <p>
        <b>Attention&nbsp;:</b><br>Pour que ce projet puisse être épinglé en page d'accueil, il est obligatoire de sélectionner à minima une image de couverture.<br>
        <br>
        <i>Si une vidéo est également sélectionnée, l'image de couverture servira en cas de non-chargement de la vidéo.</i>
      </p>
  cover:
    type: image
    label: Image de couverture…
    required: true
    translate: false
  vimeo:
    type: url
    label: …ou vidéo de couverture
    icon: vimeo
    help: Lien Vimeo vers une vidéo <b>publique</b>
    placeholder: https://vimeo.com/306221795
    translate: false
    width: 2/3
  vimeo_playback_offset:
    type: number
    label: Commencer à…
    icon: clock-o
    placeholder: '0 '
    help: Durée en secondes
    translate: false
    width: 1/3

  tab3:
    label: Méta-données
    type: tabs

  metas:
    translate: false
    type: engineer
    fields:
      metadata:
        type: select
        label: Méta-donnée
        required: true
        translate: false
        options: query
        help: >
          <a href="/panel/pages/metadatas/edit"><i class="icon icon-left fa fa-pencil"></i><span>Éditer les méta-données</span></a>
          &nbsp;/&nbsp;
          <a href="/panel/pages/metadatas/add" data-modal><i class="icon icon-left fa fa-plus-circle"></i><span>Ajouter une nouvelle méta-donnée</span></a>
        query:
          page: metadatas
          fetch: children
          value: '{{uid}}'
      fr:
        required: true
        type: text
        label: '[FR]'
        translate: false
        icon: font
        width: 1/2
      en:
        label: '[EN] (optionnel)'
        type: text
        translate: false
        icon: font
        width: 1/2

  tab4:
    label: Liens
    type: tabs

  links:
    type: engineer
    translate: false
    fieldsets:
      url:
        fields:
          url:
            label: Lien
            required: true
            translate: false
            type: url
            width: 2/4
          fr:
            label: '[FR]'
            required: true
            translate: false
            type: text
            icon: font
            width: 1/4
          en:
            label: '[EN] (optionnel)'
            type: text
            translate: false
            icon: font
            width: 1/4
      fichier:
        fields:
          url:
            label: Lien
            required: true
            translate: false
            type: select
            width: 2/4
            options: files
          fr:
            label: '[FR]'
            required: true
            translate: false
            type: text
            icon: font
            width: 1/4
          en:
            label: '[EN] (optionnel)'
            translate: false
            type: text
            icon: font
            width: 1/4

  tab5:
    label: Description
    type: tabs

  text:
    extends: _text
    label: false

  tab6:
    label: Images
    type: tabs

  gallery:
    # SEE: https://github.com/kirby-deprecated-plugins/field-engineer
    type: engineer
    translate: false
    buttons:
      - delete
      - sort-up
      - sort-down
      - sort
    fieldsets:
      image:
        fields:
          image:
            label: Image
            type: image
            translate: false
          layout:
            label: Grille
            required: true
            type: imageradio
            columns: 5
            translate: false
            options:
              -
                label: 1-1
                image: layouts/1.png
              -
                label: 2-1
                image: layouts/2.png
              -
                label: 2-2
                image: layouts/3.png
              -
                label: 1-2
                image: layouts/4.png
              -
                label: 1-3
                image: layouts/5.png
      vimeo:
        fields:
          vimeo:
            label: Vimeo
            icon: vimeo
            type: url
            width: 2/3
            translate: false
            help: Lien Vimeo vers une vidéo <b>publique</b>
            placeholder: https://vimeo.com/306221795
          playback_offset:
            label: Commencer à…
            help: Durée en secondes
            type: number
            translate: false
            icon: clock-o
            width: 1/3
            placeholder: '0'
          layout:
            label: Grille
            required: true
            type: imageradio
            columns: 5
            translate: false
            options:
              -
                label: 1-1
                image: layouts/1.png
              -
                label: 2-1
                image: layouts/2.png
              -
                label: 2-2
                image: layouts/3.png
              -
                label: 1-2
                image: layouts/4.png
              -
                label: 1-3
                image: layouts/5.png
