title: Site

options:
  changeTitle: false

tabs:
  #-----------------------------------------------------------------------------
  projects:
    label: Site
    icon: text
    columns:
      #-------------------------------------------------------------------------
      - width: 1/4
        sections:
          latest_draft_projects:
            extends: sections/projects
            headline: Projets brouillons
            status: drafts
            info: "{{ page.modified("d M") }} à {{ page.modified("H:i")}}"
          quick:
            type: fields
            fields:
              quick_access:
                label: Accès rapide
                type: pages
                translate: false
                # NOTE: change this to edit which links should be in this section
                disabled: true
      #-------------------------------------------------------------------------
      - width: 2/4
        fields:
          pinned:
            label: Projets épinglés en page d'accueil
            type: pages
            translate: false
            help: |
              <b>Attention</b> : seuls les <a href="/panel/pages/projects">projets</a> publiés peuvent être épinglés en page d'accueil.
            empty: Aucun projet en page d'accueil
            query: site.find("projects").children.listed
            image:
              query: page.panelPreviewCover
              back: black
      #-------------------------------------------------------------------------
      - width: 1/4
        sections:
          notes: sections/notes
  #-----------------------------------------------------------------------------
  options:
    label: Options
    icon: cog
    columns:
      - width: 2/3
        sections:
          seo: sections/seo
      - width: 1/3
        sections:
          social: sections/social
